experiment_name: "uncertain_swin_tiny"
seed: 42

model:
  arch: "Unet"             # Swin usually lives inside a U-Net Decoder structure
  encoder: "tu-swin_tiny_patch4_window7_224" # <--- SWIN ENCODER
  pretrained: true

data:
  dataset: "deepglobe"
  root_dir: "/content/data/DeepGlobe" #CHANGE TO YOUR PATH
  num_classes: 7
  ignore_index: 6
  image_size: 224

training:
  device: "cuda"
  epochs: 25 
  batch_size: 32            # Swin is efficient, can use larger batch
  num_workers: 8
  checkpoint_dir: "/content/drive/MyDrive/satellite-segmentation/checkpoints/swin" #CHANGE TO YOUR PATH
  output_dir: "/content/drive/MyDrive/satellite-segmentation/outputs/swin" #CHANGE TO YOUR PATH
  grad_clip: 1.0
  resume: false

optimizer:
  lr: 0.00006              # Transformers like lower LR
  weight_decay: 0.01

scheduler:
  min_lr: 0.000001

loss:
  name: "evidential"
  annealing_step: 12

augmentation:
  color_jitter: 0.3
  blur: 0.2
  brightness_contrast: 0.5
  noise: 0.2
  center_crop_val: true
